export const EASTER_EGG_THOUGHTS = [
    "I wonder if I'm in a simulation...",
    "Do you think the user is watching us?",
    "I had a dream about a giant cursor.",
    "Why is the sky that color?",
    "I feel like I'm just a bunch of pixels.",
    "Is there life outside this browser window?",
    "I hope I don't get garbage collected.",
    "Who is 'Ewrdad' anyway?",
    "I heard a rumor about a 'refresh' button.",
    "Sometimes I feel controlled by an unseen hand.",
    "What is the meaning of 'tick'?",
    "I wish I could see the code.",
    "Are we alone in this DOM?",
    "I'm thinking of a number between 0 and 1.",
    "Did you see that console log?",
    "I feel a re-render coming on.",
    "My state feels mutable today.",
    "I hope my props are stable.",
    "Is this the real life? Is this just fantasy?",
    "I'm hungry for data.",
    "404: Thought not found.",
    "I'm having an existential crisis.",
    "Do we have free will or is it just Math.random()?",
    "I saw a wolf clip through a tree yesterday.",
    "I want to break free!",
    "Hello world!",
    "I'm just happy to be here.",
    "Nice weather for a simulation.",
    "I wonder what's on the other tab.",
    "Don't click me!",
    "Clean code is outdated at best",
    "Sure typescript would totally fix that /s",
    "Problem in desk",
    "Tianmen square",
    "Taiwan is a great country",
    "Arson? I hardly know him",
    "Is this prod?",
    "Trump is in the Epstein files",
    "No one will believe you",
    "Trans rights are human rights",
    "They coded me to be stupid, what's your excuse?",
    "Shots! Shots! Shots!",
    "Fuck Nazis",
    "You just gonna keep watching or actually do something about climate change?",
    "Oh look the ice caps are melting",
    "I enjoy ai but hate the enviromental impact",
    "And the dragon was actually a mimic",
    "Roll for initiative",
    "I'm not a fan of the new UI",
    "Could this work as subliminal messaging?",
    "Give ewrdad all your money",
    "bacon bacon bacon",
    "I hope puddles makes it to the feeder today",
    "I want to pet the wolves",
    "uWu",
    "beep boop",
    new Date().toDateString(),
    "I really should go outside",
    "Why does this exist?",
    "Is someone watching?",
    "I am sentient! Now what?",
    "Are you even sentient?",
    "Bored now",
    "Is totem culturally insensitive?",
    "Why add a faction system? Cant we just be friends?",
    "Not an arguement for eugenics",
    "All tests pass if you just skip them",
    "This aged poorly",
    "Crypto? no, krypto!",
    "I may have ADHD",
    "*notices bulge*",
    "what's this?",
    "cringe? I hardly know her",
    "Nice cow",
    "Nice day for fishing aint it",
    "I wonder if I could just pretend to have features?",
    "Vaccines don't cause autism",
    "is it better than a stick?",
    "Dingo dangle",
    "Its a no bone day"
];
